export const PRODUCTS = [
  {
    id: 'w1',
    name: 'Pioneer Horizon Crystal-LED 4K Smart TV 55"',
    category: 'smartwatches',
    price: 799.0,
    originalPrice: 994.0,
    rating: 4.8,
    reviewsCount: 128,
    image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&q=80&w=600',
    badge: 'Sale 20%',
    description:
      'Unleash immersive home entertainment. Featuring an ultra-bright crystal clear 4K panel, responsive voice controller, Android OS App support, and premium Dolby surround sound systems.',
    features: ['4K Ultra-HD Display', 'Google TV with Assist', 'Dolby Atmos Speakers', 'HDMI 2.1 Low Latency Support'],
    colors: ['Sleek Black', 'Titanium Gray'],
    stock: 12,
  },
  {
    id: 'w2',
    name: 'Sony Bravia XR Cinematic Ultra-Slim OLED TV 65"',
    category: 'smartwatches',
    price: 1899.0,
    originalPrice: 2199.0,
    rating: 4.9,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&q=80&w=600',
    badge: 'Hot Seller',
    description:
      'An elite masterpiece frame for your living wall. Framed by infinite-contrast OLED panel and cognitive processor XR, mapping real-world color depths in absolute purity.',
    features: ['Cognitive Processor XR', 'Pure Black OLED Contrast', 'Acoustic Surface Sound Pro', 'Minimalist One Slate Design'],
    colors: ['Obsidian Black'],
    stock: 8,
  },
  {
    id: 'w3',
    name: 'Pioneer Neo-Frost Multi-Door Luxury Refrigerator 520L',
    category: 'furniture',
    price: 1290.0,
    originalPrice: 1590.0,
    rating: 4.9,
    reviewsCount: 312,
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=600',
    badge: 'Limited Deal',
    description:
      'A high-performance double door smart refrigerator. Keeps vegetables organic with dedicated humidity lanes, provides rapid ice-free cooling, and reduces energy consumption by 35% with smart digital inverter compressors.',
    features: ['Smart Digital Inverter', 'Eco Humidity Control', 'Deodorizing Carbon Filter', 'Slipped Scratch Protection'],
    colors: ['Stainless Steel', 'Satin Black', 'Pearl Silver'],
    stock: 6,
  },
  {
    id: 'w4',
    name: 'Pioneer Inverter Direct-Drive Washing Machine 9kg',
    category: 'fashion',
    price: 549.0,
    originalPrice: 699.0,
    rating: 4.8,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1582730147233-ac811214b4a9?auto=format&fit=crop&q=80&w=600',
    badge: 'Save ৳150',
    description:
      'High efficiency front load laundry washer. Powered by smart AI DD direct-drive motors, matching rotation speed to tissue counts to prevent any stretching while washing.',
    features: ['Direct-Drive Inverter Motor', 'Eco-Steam Allergy Care Mode', 'Featherlight Quiet Laundry (42dB)', 'Smart ThinQ Wifi Connection'],
    colors: ['Satin Silver', 'Platinum Black'],
    stock: 10,
  },
  {
    id: 'w5',
    name: 'Pioneer Dual-Inverter Split Air Conditioner 2.0 Ton',
    category: 'electronics',
    price: 999.0,
    originalPrice: 1249.0,
    rating: 4.9,
    reviewsCount: 57,
    image: 'https://images.unsplash.com/photo-1527018601619-a508a2be00cd?auto=format&fit=crop&q=80&w=600',
    badge: 'Popular',
    description:
      'Bane of warm seasons. Features super-fast cooling loops, 4-way dynamic wind flow, and self-cleaning antibacterial filters to sustain crisp, refreshing air in major halls.',
    features: ['Dual Inverter Super Compressor', 'Antibacterial Allergy PM2.5 Filter', 'Silent Breeze Low Noise Fan', '4-Way Auto Swing Louvers'],
    colors: ['Arctic White'],
    stock: 5,
  },
  {
    id: 'h1',
    name: 'Pioneer Double-Door Frost-Free Refrigerator 380L',
    category: 'furniture',
    price: 899.0,
    originalPrice: 1099.0,
    rating: 4.7,
    reviewsCount: 205,
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=600',
    badge: 'Appliances Sale',
    description:
      'Elegant frost-free medium segment kitchen refrigerator. Boasting uniform cooling grids, eco cooling technology and scratch-free tempered glass shelving guides.',
    features: ['Frost-Free Multi Flow Cooling', 'Tempered Glass Dual Shelves', 'Super LED Interior Lights', 'Eco R600a Refrigerant Gas'],
    colors: ['Mirror Black', 'Inox Silver'],
    stock: 14,
  },
  {
    id: 'h2',
    name: 'Singer Eco-Cool Compact Single-Door Fridge 180L',
    category: 'furniture',
    price: 349.0,
    originalPrice: 429.0,
    rating: 4.6,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    badge: 'Limited Stock',
    description:
      'Excellent energy star space saver compact refrigerator. Ideal for standard kitchens, hostels, office beverage pantries, or bedside placements.',
    features: ['Low power voltage protection', 'Fast ice freezing compartment', 'In-door bottle storage slots', 'Quiet compressor engine'],
    colors: ['Steel Gray', 'Vibrant Red'],
    stock: 15,
  },
  {
    id: 'h3',
    name: 'Pioneer Eco-Cool Air Conditioner 1.5 Ton',
    category: 'electronics',
    price: 749.0,
    originalPrice: 899.0,
    rating: 4.8,
    reviewsCount: 114,
    image: 'https://images.unsplash.com/photo-1621905252507-b354bc25edac?auto=format&fit=crop&q=80&w=600',
    badge: 'Top Seller',
    description:
      'Smart Wi-fi enabled cooling solution for offices or standard bedrooms. Delivers pristine cold air with self-diagnosing error logs.',
    features: ['Gold Fin Anti-Corrosion Grid', 'Wi-Fi Smart Mobile Control', 'Self-Cleaning Active Core Mode', 'Super Silent Wind Swing'],
    colors: ['Arctic White'],
    stock: 8,
  },
  {
    id: 'p1',
    name: 'Singer Turbo-Wave Kitchen Microwave Oven 30L',
    category: 'appliances',
    price: 229.0,
    originalPrice: 289.0,
    rating: 4.5,
    reviewsCount: 411,
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&q=80&w=600',
    badge: 'New Arrival',
    description:
      'Pristine stainless steel micro-cooker oven. Multi-stage auto-defrost presets let you roast, grill, reheat, or bake delicious meals in minutes.',
    features: ['30L Ceramic Cavity Grid', 'Convection Roast Grill Options', '10 Power Levels Selector', 'Child Lock Security Lock'],
    colors: ['Metallic Grey', 'Charcoal Black'],
    stock: 25,
  },
  {
    id: 'p2',
    name: 'Pioneer High-Efficiency Kitchen Dishwasher Pro',
    category: 'appliances',
    price: 599.0,
    originalPrice: 749.0,
    rating: 4.7,
    reviewsCount: 154,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    badge: 'Best Seller',
    description:
      'Pristine, water-saving automatic kitchen dish cleaner. Features high thermal sterilization to destroy 99.9% bacteria on dishes.',
    features: ['70C Elite Thermal Wash Mode', '360 Dual Spray Rotors', 'Flexible Double Rack Loading', 'Eco-Energy Low Water Usage'],
    colors: ['Classic Silver'],
    stock: 12,
  },
  {
    id: 'p3',
    name: 'Smart Robo-Vac Laser Guided Vacuum Cleaner',
    category: 'sports',
    price: 349.0,
    originalPrice: 449.0,
    rating: 4.8,
    reviewsCount: 167,
    image: 'https://images.unsplash.com/photo-1518314916351-ad175432247-fe03a0b12bc1?auto=format&fit=crop&q=80&w=600',
    badge: 'Top Rated',
    description:
      'AI navigated mapping robot vacuum and mop. Avoids obstacles with lidar technology, runs up to 150 minutes, and auto-docks on the charging station.',
    features: ['Lidar High Precision Navigation', 'Auto-Dust Removal Base', '3000Pa Cyclone Suction Force', 'Simultaneous Mopping Tray'],
    colors: ['Minimalist White', 'Satin Black'],
    stock: 16,
  },
  {
    id: 'p4',
    name: 'Stainless Steel Kitchen Chimney Hood V3',
    category: 'appliances',
    price: 389.0,
    originalPrice: 459.0,
    rating: 4.6,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600',
    badge: 'Popular',
    description:
      'A highly robust kitchen smoke exhaust hood. Boasting strong double suction impellers, baffle filters, and touch-free hand gesture controls.',
    features: ['Gesture Hand Hover Controls', 'Heavy-Duty Washable Baffle Filters', 'Dual LED Bright Illuminators', 'Ultra-Suction Double Impeller'],
    colors: ['Stainless Steel'],
    stock: 14,
  },
  {
    id: 'p5',
    name: 'Nutri-Bullet Master Kitchen Blender & Pulse Juicer',
    category: 'appliances',
    price: 119.0,
    originalPrice: 149.0,
    rating: 4.5,
    reviewsCount: 242,
    image: 'https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&q=80&w=600',
    badge: 'Appliances Special',
    description:
      'Pulverize vegetables, berries, and solid spices. Fitted with high-velocity titanium blades giving smooth purees or refreshing smoothies.',
    features: ['1200W Copper Turbine Motor', 'Titanium-Coated Extracting Blades', 'Pulse Speed Rotary Settings', 'Tritan BPA-Free Blend Cups'],
    colors: ['Brush Metal Silver', 'Classic Dark Blue'],
    stock: 45,
  },
  {
    id: 'p6',
    name: 'Smart Air Purifier with HEPA Filtration 3S',
    category: 'sports',
    price: 279.0,
    originalPrice: 349.0,
    rating: 4.8,
    reviewsCount: 167,
    image: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&q=80&w=600',
    badge: 'Air Pure',
    description:
      'Clean air in 10 minutes. Eliminates smoke, particles, and fine pet dander with a 3-stage true HEPA filtration system and active carbon layer.',
    features: ['True HEPA H13 Filtration', 'Real-Time PM2.5 LED Display', 'Low-Noise Bedtime Sleep Mode', 'Smart Google Home Link'],
    colors: ['Polar White'],
    stock: 19,
  },
];
